stages:
  load_data:
    cmd: python src/stage_01_load_save.py --config=config/config.yaml
    deps:
      - src/stage_01_load_save.py
      - src/utils/all_utils.py
      - config/config.yaml 

    outs:
      - artifacts/raw_local_dir/data.csv

    
  split_data:
    cmd: python src/stage02_split_data.py
    deps:
      - src/stage02_split_data.py
      - src/utils/all_utils.py
      - config/config.yaml 
    params:
      - base.random_state
      - base.test_size      #Dont need to specify parameters in deps as its already tracking using params. 
    outs:
      - artifacts/split_data_dir/train.csv
      - artifacts/split_data_dir/test.csv